@startuml
usecase Программирование
usecase Императивное
usecase Декларативное
usecase Структурное
usecase "Не структурное"
usecase Процедурное
usecase "Объектно-ориентированное"
usecase Функциональное
usecase Логическое

Программирование --> Императивное
Программирование --> Декларативное
Императивное --> Структурное
Императивное --> "Не структурное"
Декларативное --> Логическое
Декларативное --> Функциональное
Структурное --> Процедурное
Структурное --> "Объектно-ориентированное"
Структурное --> Функциональное

@enduml